"""modified Category table to include image links.

Revision ID: b66c8fd820fa
Revises: 0419907f8237
Create Date: 2020-03-30 03:55:05.145335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66c8fd820fa'
down_revision = '0419907f8237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'category', ['image'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'image')
    # ### end Alembic commands ###
