"""rathada

Revision ID: e31ad3e33bbf
Revises: 25b6580be231
Create Date: 2020-03-30 05:22:50.687817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31ad3e33bbf'
down_revision = '25b6580be231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('state', table_name='address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('state', 'address', ['state'], unique=True)
    # ### end Alembic commands ###
